services:
  # Backend API Service
  - type: web
    name: soundbites-quiz-backend
    runtime: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://otis.soundbites.com
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: soundbites-db
          property: connectionString
    healthCheckPath: /health

  # Frontend Static Site
  - type: web
    name: soundbites-quiz-frontend
    runtime: static
    plan: free
    buildCommand: echo "No build needed - static site"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /
        destination: /index.html
      - type: rewrite
        source: /admin
        destination: /admin/login.html
      - type: redirect
        source: /api/*
        destination: https://soundbites-quiz-backend.onrender.com/api/*

# PostgreSQL Database
databases:
  - name: soundbites-db
    databaseName: soundbites
    user: soundbites
    plan: free
